---
- name: Create working directory
  file: path={{ REPORT_DIR }} state=directory
  ignore_errors: yes

- name: Copy the network_report script
  copy: src=network_report.sql dest=/usr/share mode=0755

- name: Add report header
  shell: ( echo "+-------------------------+"; echo "| Cloud Network Report    |"; echo "+-------------------------+"; ) >> {{ REPORT_DIR }}/os_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log 
  
- name: Execute network report
  shell: chdir=/usr/bin mysql -u root --password={{ MYSQLPASS }} --table < /usr/share/network_report.sql >> {{ REPORT_DIR }}/os_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log